// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


// Endereço e chave pública do projeto Supabase do AVANTE.
//
// Ficam no código de propósito. Estes dois valores são públicos por definição:
// mesmo vindos de variável de ambiente, eles terminam dentro do JavaScript que
// o navegador baixa — é assim que o Supabase foi desenhado. Quem protege os
// dados dos pacientes é a RLS do banco, não o segredo destes valores.
//
// Servem de rede de segurança: sem eles, qualquer tropeço na injeção das
// variáveis em tempo de build derruba o app inteiro na primeira tela, com uma
// mensagem que não diz o que fazer. A variável de ambiente continua tendo
// prioridade, então dá para apontar para outro projeto sem mexer no código.
const SUPABASE_URL_PADRAO = 'https://lpszrxuqoxgrtqzpgerz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY_PADRAO = 'sb_publishable_6K0QYLgMB3K9os4C4CiKnA_Nckxn1kN';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  //
  // ATENÇÃO — tem que ser notação de ponto. A config da Lovable injeta estas
  // variáveis como `define: { "import.meta.env.VITE_SUPABASE_URL": "..." }`, e
  // o define do Vite substitui a expressão exata. Com colchetes
  // (`import.meta.env['VITE_SUPABASE_URL']`) nada casa, o termo vira undefined
  // e sobra só o process.env — que no navegador é um objeto vazio. Era assim
  // que estava, e o app quebrava na Vercel com "Missing Supabase environment
  // variable(s)" antes mesmo de renderizar.
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env['SUPABASE_URL'] || SUPABASE_URL_PADRAO;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env['SUPABASE_PUBLISHABLE_KEY'] ||
    SUPABASE_PUBLISHABLE_KEY_PADRAO;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

